# Generated by Django 4.2.30 on 2026-05-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('light', 'Освещение'), ('climate', 'Климат'), ('security', 'Безопасность'), ('kitchen', 'Кухня'), ('sensor', 'Датчик'), ('media', 'Медиа'), ('other', 'Другое')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('off', 'Выключено'), ('on', 'Включено'), ('error', 'Ошибка'), ('maintenance', 'Обслуживание')], default='off', max_length=20)),
                ('value', models.CharField(blank=True, default='', max_length=100)),
                ('power_watts', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'ordering': ['room', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='core.home')),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
                'ordering': ['home', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(choices=[('temperature', 'Температура'), ('humidity', 'Влажность'), ('motion', 'Движение'), ('energy', 'Энергопотребление'), ('light', 'Освещённость'), ('other', 'Другое')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.device')),
            ],
            options={
                'verbose_name': 'Показание датчика',
                'verbose_name_plural': 'Показания датчиков',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('turn_on', 'Включить'), ('turn_off', 'Выключить'), ('toggle', 'Переключить'), ('set_temperature', 'Установить температуру'), ('set_brightness', 'Установить яркость'), ('set_color', 'Установить цвет'), ('set_volume', 'Установить громкость'), ('start', 'Запустить'), ('stop', 'Остановить'), ('lock', 'Заблокировать'), ('unlock', 'Разблокировать')], max_length=30)),
                ('value', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_actions', to='core.device')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.scenario')),
            ],
            options={
                'verbose_name': 'Действие сценария',
                'verbose_name_plural': 'Действия сценариев',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor', models.IntegerField(default=1)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.home')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['home', 'floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('info', 'Информация'), ('command', 'Команда'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('scenario', 'Сценарий'), ('sensor', 'Датчик')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.device')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.home')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Журнал событий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(choices=[('turn_on', 'Включить'), ('turn_off', 'Выключить'), ('toggle', 'Переключить'), ('set_temperature', 'Установить температуру'), ('set_brightness', 'Установить яркость'), ('set_color', 'Установить цвет'), ('set_volume', 'Установить громкость'), ('start', 'Запустить'), ('stop', 'Остановить'), ('lock', 'Заблокировать'), ('unlock', 'Разблокировать')], max_length=30)),
                ('is_enabled', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='core.device')),
            ],
            options={
                'verbose_name': 'Возможность устройства',
                'verbose_name_plural': 'Возможности устройств',
                'ordering': ['device', 'action_name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.room'),
        ),
    ]
